### ISSUE TITLE
ImportError for markdown2html_mistune on OS X

### ISSUE THREAD

**Issue by robintw** [pathomx/pathomx#32]
I'm trying to install from the Github repo on OS X, following the developer installation instructions. I've got all of the dependencies installed including IPython, but when I run pathomx I get:

```
DEBUG:root:Loading globals.py
DEBUG:root:Loading settings...
DEBUG:root:Setting up managers...
DEBUG:yapsy:PluginManagerSingleton initialised
DEBUG:root:Loading ui.py
DEBUG:root:Loading data.py
DEBUG:root:Loading views.py
DEBUG:root:Loading translate.py
Traceback (most recent call last):
  File "Pathomx.py", line 7, in <module>
    from pathomx import Pathomx
  File "/Users/robin/code/pathomx/pathomx/Pathomx.py", line 50, in <module>
    from . import ui
  File "/Users/robin/code/pathomx/pathomx/ui.py", line 40, in <module>
    from IPython.nbconvert.filters.markdown import markdown2html_mistune
ImportError: cannot import name markdown2html_mistune
```

I'm running Python 2.7 and IPython 2.4.0. Interestingly, when I try and import that module I get the following results:

```python
>>> import IPython.nbconvert.filters.markdown as m
>>> dir(m)
['BytesIO', 'ConversionException', 'NodeJSMissing', 'TextIOWrapper', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_node', '_verify_node', 'cast_bytes', 'check_version', 'get_output_error_code', 'markdown2html', 'markdown2html_marked', 'markdown2html_pandoc', 'markdown2latex', 'markdown2rst', 'marked', 'os', 'pandoc', 'print_function', 'subprocess', 'warnings']
```

It seems like lots of the other markdown conversion functions are there, but not the one that pathomx uses.

Any ideas?

**Comment by mfitzp** [comment]
Thanks for the bug report @robintw ...I suspect the issue is that the current codebase works with a pre-release version of IPython (installed from the [IPython]() here on Github) for the cluster support. My current release reports `3.0.0-dev`. 

Are you able to install that version? Thankfully I think the final 3.0 release is a few weeks away, so hopefully this issue won't exist for long.

**Comment by robintw** [comment]
Yup, that solved it - thanks. As you said, should all be fine in a few weeks time.
